### ISSUE TITLE
Outdated chart version in concourse new repo

### ISSUE THREAD

**Issue by failytaler** [concourse/concourse-chart#26]
The last version I see here is 8.4.0, however last update in https://concourse-charts.storage.googleapis.com/ - concourse 8.2.6.
The last version in stable repo is 8.3.7. How should we proceed with migration?

**Comment by RaphaelVogel** [comment]
The current situation is very unpleasant. The old helm chart in https://github.com/helm/charts/tree/master/stable/concourse is deprecated and the new chart in https://concourse-charts.storage.googleapis.com is not up to date?
```
$ helm search repo concourse                                                                                                                                                                                                                                   
NAME               	CHART VERSION	APP VERSION	DESCRIPTION
concourse/concourse	8.2.6        	5.6.0      	Concourse is a simple and scalable CI system.
```

**Comment by u2g-tg** [comment]
Hey yeah, whats happening here? Your Helm chart repo isn't updated with the latest versions you have in the source code.

**Comment by u2g-tg** [comment]
@taylorsilva

**Comment by taylorsilva** [comment]
Hey, we have been really bad about this as we've been trying to figure out the workflow for the whole team internally (thinking about different versioning strategies, the pros-cons). The current version is now updated as of yesterday. The community can continue to contribute to `master` now and changes should get shipped out shortly after.

Right now all changes on master are on the current chart version of `8.4.1` which is coming from the `release/5.7.x` branch. Currently all changes going on master also go on the latest release branch and then we publish the chart from [our CI]. Because we're just starting with this workflow the version numbers you'll see on `master` vs the `release/#.#.x` branches are misaligned. They will align and make more sense once the next version of the Concourse binary is out.

Let me know what you all think and if there are any other concerns. Sorry about the sour experience we've given over the past few weeks.

[our CI]: https://nci.concourse-ci.org/teams/main/pipelines/release-5.7.x/jobs/ship-chart/builds/5

**Comment by taylorsilva** [comment]
Closing because we've gotten better at releasing more frequently

<img width="263" alt="image" src="https://user-images.githubusercontent.com/4583837/83276837-34724f00-a19f-11ea-99c3-85762607ef65.png">
