### ISSUE TITLE
Web-app expects incorrect secret key

### ISSUE THREAD

**Issue by grenader** [concourse/concourse-chart#289]
Steps to reproduce:

```
helm repo add concourse https://concourse-charts.storage.googleapis.com/
helm install con1 concourse/concourse

... wait
kubectl get pod
```
The web-application pod will not start.
"describe" it and see the following error:
```
Error: couldn't find key postgresql-password in Secret default/con1-postgresql
```

"describe" the secret, and observe that it has a different key.
```
kubectl describe secret con1-postgresql
```
Output:
```
....
Data
====
postgres-password:  10 bytes
```

The problem is that web app is expecting an incorrect key in the secret.

**Comment by chris-sanders** [comment]
I've just hit this too, the reason this is happening is that the Bitnami chart was given a **major** version change inside of the concourse charts **minor** version change.

During that change Bitnami changed the password field, but that's not all that was changed. See the reference https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/

Anyone attempting an upgrade is going to fail due to this change. Keys were relocated for authentication, persistence, and the version of postgres was updated. Even if the user gets all of the mapping correct the new chart won't read the database w/o explicitly setting the version or performing a manual upgrade. Finally, the new chart changes the statefulset which you can't do.

Honestly I think this chart should revert the Bitnmai sub-chart bump, and release a new **major** version of the chart that includes the bump tested for the new values.

**Comment by grenader** [comment]
Right, @chris-sanders 
I have also found that the new Bitnamy Postgres has created a problem. Manual recreation of the secret with additional keys did not help.
We are successfully using v16.1.16 of your chart now.

**Comment by xtremerui** [comment]
[16.1.19](https://github.com/concourse/concourse-chart/releases/tag/v16.1.19) is released with the revert of postgresql bump. 

https://github.com/concourse/concourse-chart/issues/290 is created to track the work for concourse-chart next major release.
