### ISSUE TITLE
Namespace creation is not very optional

### ISSUE THREAD

**Issue by jonkerj** [concourse/concourse-chart#3]
**Describe the bug**
When setting `concourse.web.kubernetes.createTeamNamespaces: false`, namespaces are not created. But, `web-rolebindings.yaml` does not contain a proper conditional to survive the absence of team namespaces, thus causing tiller to error:

```
$ helm install --set concourse.web.kubernetes.createTeamNamespaces=false /path/to/concourse-chart
Error: release concourse failed: namespaces "concourse-main" not found
```

This used to be helm/charts#18008

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jonkerj** [comment]
Hi, any chance someone could actually look at this bug and my (trivial) PR?

**Comment by jonkerj** [comment]
Hi, can someone please take a look at this?

**Comment by taylorsilva** [comment]
Hey @jonkerj I'm taking a look at this now. Sorry about the delay. I'll update in the PR.

**Comment by taylorsilva** [comment]
@jonkerj replying in here as it's usually easier for people to find issues vs PR's

I'm thinking the fix for this may actually be adding a comment to [`values.yaml` here](https://github.com/concourse/concourse-chart/blob/741f930d81b5c8776af4fb6f8c7d52875ae927c4/values.yaml#L344-L346) to explain the following:

By default the chart uses k8s secrets as its credential manager (`concourse.web.kubernetes.enabled=true`).
When enabled the chart expects that namespaces are going to created by the chart or the user. If you set `createTeamNamespaces` to `false` then it's expected that the user will create the appropriate namespaces **before** the chart is deployed, like this:

```
kubectl create namespace release-name-teamName
helm install --set concourse.web.kubernetes.createTeamNamespaces=false /path/to/concourse-chart
```
If you only set `createTeamnamespaces` to false and don't also set `concourse.web.kubernetes.enabled` to false, when the concourse end-user tries to use a secret in their pipeline they'll get the following error:
```
failed to interpolate task config: 
  Finding variable 'foo': secrets "pipeline.foo" is forbidden: 
    User "system:serviceaccount:topgun-k8s-cm-31628541:topgun-k8s-cm-31628541-web"
    cannot get resource "secrets" in API group "" in the namespace "topgun-k8s-cm-31628541-main"
```

If you don't want team namespaces and the web role bindings then `concourse.web.kubernetes.enabled` should be set to true.

What do you think about this?

**Comment by jonkerj** [comment]
Hi Taylor,

Took me a while to get back at you, since I am not really sure what would work for me. My original usecase was to run Concourse on k8s with as least "bells and whistles" thus without team namespaces, credential management, etc. In the meanwhile, I learned that k8s credential management is probably something I do want, which renders my issue obsolete.

But, I do think the chart could give a more user friendly feedback if a less than optimal combination of values is used (ie, `kubernetes: true` + `createTeamNamespaces: false`), instead of failing hard. I think I've seen such 'checks' in other charts, but I am not an expert on this matter unfortunately.

I think your suggestion to comment on this in `values.yaml` is a good start.
